"""
SmritiSaathi — Auth Service

Handles user registration, login, and token generation.
All passwords are hashed with bcrypt. No plaintext storage.
"""

from typing import Optional
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import hash_password, verify_password, create_access_token
from app.models.user import User, UserRole
from app.models.patient import PatientProfile
from app.models.caregiver import CaregiverProfile, PatientCaregiverLink, LinkStatus
from app.schemas.auth import (
    PatientRegisterRequest,
    CaregiverRegisterRequest,
    TokenResponse,
)


async def register_patient(
    data: PatientRegisterRequest, db: AsyncSession
) -> TokenResponse:
    """
    Register a new patient:
    1. Check email uniqueness
    2. Create User record with hashed password
    3. Create PatientProfile
    4. Link to caregiver if invitation code provided
    5. Return JWT token
    """
    # Check for existing email
    existing = await db.execute(select(User).where(User.email == data.email))
    if existing.scalar_one_or_none():
        raise ValueError("An account with this email already exists")

    # Create user
    user = User(
        email=data.email,
        password_hash=hash_password(data.password),
        role=UserRole.PATIENT,
        is_active=True,
    )
    db.add(user)
    await db.flush()  # Get user.id

    # Create patient profile
    profile = PatientProfile(
        user_id=user.id,
        full_name=data.full_name,
        date_of_birth=data.date_of_birth,
        gender=data.gender,
        preferred_language=data.preferred_language,
        contact_phone=data.contact_phone,
        address=data.address,
        emergency_contact_name=data.emergency_contact_name,
        emergency_contact_phone=data.emergency_contact_phone,
        consent_acknowledged=data.consent_acknowledged,
        baseline_completed=False,
    )
    db.add(profile)
    await db.flush()

    # Link to caregiver if invitation code provided
    if data.caregiver_invitation_code:
        caregiver_result = await db.execute(
            select(CaregiverProfile).where(
                CaregiverProfile.invitation_code == data.caregiver_invitation_code
            )
        )
        caregiver = caregiver_result.scalar_one_or_none()
        if caregiver:
            link = PatientCaregiverLink(
                patient_profile_id=profile.id,
                caregiver_profile_id=caregiver.id,
                status=LinkStatus.ACTIVE,
            )
            db.add(link)

    # Generate token
    token = create_access_token(
        data={"sub": str(user.id), "role": user.role.value}
    )

    return TokenResponse(
        access_token=token,
        user_id=user.id,
        role=user.role.value,
        full_name=profile.full_name,
        baseline_completed=False,
    )


async def register_caregiver(
    data: CaregiverRegisterRequest, db: AsyncSession
) -> TokenResponse:
    """
    Register a new caregiver:
    1. Check email uniqueness
    2. Create User record with hashed password
    3. Create CaregiverProfile with auto-generated invitation code
    4. Return JWT token
    """
    # Check for existing email
    existing = await db.execute(select(User).where(User.email == data.email))
    if existing.scalar_one_or_none():
        raise ValueError("An account with this email already exists")

    # Create user
    user = User(
        email=data.email,
        password_hash=hash_password(data.password),
        role=UserRole.CAREGIVER,
        is_active=True,
    )
    db.add(user)
    await db.flush()

    # Create caregiver profile (invitation_code auto-generated by model)
    profile = CaregiverProfile(
        user_id=user.id,
        full_name=data.full_name,
        contact_phone=data.contact_phone,
        relationship_type=data.relationship_type,
        consent_acknowledged=data.consent_acknowledged,
    )
    db.add(profile)
    await db.flush()

    # Generate token
    token = create_access_token(
        data={"sub": str(user.id), "role": user.role.value}
    )

    return TokenResponse(
        access_token=token,
        user_id=user.id,
        role=user.role.value,
        full_name=profile.full_name,
        baseline_completed=None,
    )


async def login_user(
    email: str, password: str, db: AsyncSession
) -> TokenResponse:
    """
    Authenticate user:
    1. Find user by email
    2. Verify password hash
    3. Return JWT token with role-specific info
    """
    result = await db.execute(select(User).where(User.email == email))
    user = result.scalar_one_or_none()

    if user is None or not verify_password(password, user.password_hash):
        raise ValueError("Invalid email or password")

    if not user.is_active:
        raise ValueError("Account is deactivated")

    # Get profile info based on role
    full_name = ""
    baseline_completed = None

    if user.role == UserRole.PATIENT:
        profile_result = await db.execute(
            select(PatientProfile).where(PatientProfile.user_id == user.id)
        )
        profile = profile_result.scalar_one_or_none()
        if profile:
            full_name = profile.full_name
            baseline_completed = profile.baseline_completed
    elif user.role == UserRole.CAREGIVER:
        profile_result = await db.execute(
            select(CaregiverProfile).where(CaregiverProfile.user_id == user.id)
        )
        profile = profile_result.scalar_one_or_none()
        if profile:
            full_name = profile.full_name

    token = create_access_token(
        data={"sub": str(user.id), "role": user.role.value}
    )

    return TokenResponse(
        access_token=token,
        user_id=user.id,
        role=user.role.value,
        full_name=full_name,
        baseline_completed=baseline_completed,
    )
